# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: enums/status.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class Status(betterproto.Enum):
    """Enum definition"""

    UNKNOWN = 0
    ACTIVE = 1
    INACTIVE = 2
