# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: models/address.proto, models/person.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto

from protogen import enums


@dataclass
class Address(betterproto.Message):
    street: str = betterproto.string_field(1)
    city: str = betterproto.string_field(2)
    zip: str = betterproto.string_field(3)


@dataclass
class Person(betterproto.Message):
    name: str = betterproto.string_field(1)
    id: int = betterproto.int32_field(2)
    email: str = betterproto.string_field(3)
    phone_numbers: List[str] = betterproto.string_field(4)
    address: "Address" = betterproto.message_field(5)
    status: enums.Status = betterproto.enum_field(6)
