//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.soapweather.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type</p>.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.</p>
 * 
 * <pre>{@code
 * <complexType>
 *   <complexContent>
 *     <restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       <sequence>
 *         <element name="weatherInfo" type="{https://example.com/weather}WeatherInfo"/>
 *       </sequence>
 *     </restriction>
 *   </complexContent>
 * </complexType>
 * }</pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "weatherInfo"
})
@XmlRootElement(name = "getWeatherResponse")
public class GetWeatherResponse {

    @XmlElement(required = true)
    protected WeatherInfo weatherInfo;

    /**
     * Gets the value of the weatherInfo property.
     * 
     * @return
     *     possible object is
     *     {@link WeatherInfo }
     *     
     */
    public WeatherInfo getWeatherInfo() {
        return weatherInfo;
    }

    /**
     * Sets the value of the weatherInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeatherInfo }
     *     
     */
    public void setWeatherInfo(WeatherInfo value) {
        this.weatherInfo = value;
    }

}
