//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.5 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package com.example.soapweather.model;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.soapweather.model package. 
 * <p>An ObjectFactory allows you to programmatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.soapweather.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetWeatherRequest }
     * 
     * @return
     *     the new instance of {@link GetWeatherRequest }
     */
    public GetWeatherRequest createGetWeatherRequest() {
        return new GetWeatherRequest();
    }

    /**
     * Create an instance of {@link GetWeatherResponse }
     * 
     * @return
     *     the new instance of {@link GetWeatherResponse }
     */
    public GetWeatherResponse createGetWeatherResponse() {
        return new GetWeatherResponse();
    }

    /**
     * Create an instance of {@link WeatherInfo }
     * 
     * @return
     *     the new instance of {@link WeatherInfo }
     */
    public WeatherInfo createWeatherInfo() {
        return new WeatherInfo();
    }

    /**
     * Create an instance of {@link UpdateTemperatureRequest }
     * 
     * @return
     *     the new instance of {@link UpdateTemperatureRequest }
     */
    public UpdateTemperatureRequest createUpdateTemperatureRequest() {
        return new UpdateTemperatureRequest();
    }

    /**
     * Create an instance of {@link UpdateTemperatureResponse }
     * 
     * @return
     *     the new instance of {@link UpdateTemperatureResponse }
     */
    public UpdateTemperatureResponse createUpdateTemperatureResponse() {
        return new UpdateTemperatureResponse();
    }

}
