source run_parts/common_declarations.sh
source run_parts/java_program_declarations.sh
source run_parts/python_program_declarations.sh

# Function declarations
function check_protos() {
    protoc --proto_path=protos --descriptor_set_out=/dev/null $(find protos -name "*.proto")

    # Or, to generate schema bundle
    # protoc --proto_path=protos --include_imports --descriptor_set_out=protos.pb $(find protos -name "*.proto")
}

# Navigate to root dir
cd ..
log "root dir: $(pwd)"

# Check proto files
if check_protos ; then
    log "proto files are OK"
else
    log "proto files are NOT OK"
    exit 1
fi

# Clear files generated by compiling proto files.
rmGenJava
rmGenPython

# Compile proto
genJava
genPython

# Compile programs
compileJava

# Run programs
divideOutput
runJava demo
divideOutput
runPython demo
divideOutput


runJava serialize
runPython deserialize
divideOutput

runPython serialize
runJava deserialize
